name: Deploy to LWS cPanel

on:
   push:
      branches: [deploy]

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repository
           uses: actions/checkout@v4

         - name: Setup Node.js
           uses: actions/setup-node@v4
           with:
              node-version: '20'
              cache: 'npm'

         - name: Install Dependencies
           run: |
              npm ci
              npm install prisma@latest --save-dev

         - name: Create Prisma Schema
           run: |
              cat > prisma/schema.prisma << 'EOL'
              generator client {
                provider = "prisma-client-js"
              }

              datasource db {
                provider = "mysql"
                url      = env("DATABASE_URL")
              }

              model Winner {
                id         Int       @id @default(autoincrement())
                fullName   String?
                email      String    @unique
                phone      String?
                profession String?
                level      String
                score      Int
                wonLevels  String
                winnerCode String    @unique
                createdAt  DateTime  @default(now())
                updatedAt  DateTime  @updatedAt
              }
              EOL

         - name: Generate Prisma Client
           run: |
              npx prisma generate
              npx prisma db push --accept-data-loss
           env:
              DATABASE_URL: ${{ secrets.DATABASE_URL }}

         - name: Build Application
           env:
              DATABASE_URL: ${{ secrets.DATABASE_URL }}
           run: npm run build

         # Rest of your deployment steps...
