name: Deploy to cPanel

on:
   push:
      branches: [deploy] # Adjust to match your deployment branch

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repository
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: '20'
              cache: 'npm'

         - name: Install Dependencies
           run: npm ci

         - name: Generate Prisma Client
           run: npx prisma generate

         - name: Build Application
           env:
              DATABASE_URL: ${{ secrets.DATABASE_URL }}
           run: npm run build

         - name: Prepare Deployment Files
           run: |
              mkdir -p deployment/quiz

              # Copy standalone build files
              cp -r .next/standalone/* deployment/quiz/

              # Copy static files
              cp -r .next/static deployment/quiz/.next/static

              # Copy required project files
              cp package.json deployment/quiz/
              cp -r public deployment/quiz/public

              # Make sure `server.js` exists
              chmod +x deployment/quiz/server.js || echo "⚠️ server.js not found!"

         - name: FTP Deploy
           uses: SamKirkland/FTP-Deploy-Action@v4.3.4
           with:
              server: ${{ secrets.FTP_SERVER }}
              username: ${{ secrets.FTP_USERNAME }}
              password: ${{ secrets.FTP_PASSWORD }}
              local-dir: deployment/quiz/
              server-dir: / # Adjusted to match your setup
              exclude: |
                 **/.git*
                 **/.git*/**
                 **/node_modules/**
                 README.md
                 .env*
