name: Deploy to cPanel

on:
   push:
      branches: [deploy]

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repository
           uses: actions/checkout@v3

         - name: Setup Node.js
           uses: actions/setup-node@v3
           with:
              node-version: '20'
              cache: 'npm'

         - name: Install Dependencies
           run: npm ci

         - name: Generate Prisma Client
           run: npx prisma generate

         - name: Build Application
           env:
              DATABASE_URL: ${{ secrets.DATABASE_URL }}
           run: npm run build

         - name: Debug Build Output
           run: |
              echo "Checking build output..."
              ls -la .next/ || echo "⚠️ .next directory not found!"
              ls -la .next/standalone/ || echo "⚠️ .next/standalone directory not found!"
              ls -la .next/static/ || echo "⚠️ .next/static directory not found!"

         - name: Prepare Deployment Files
           run: |
              echo "Creating deployment directory..."
              mkdir -p deployment/quiz/.next/static || echo "⚠️ Failed to create .next/static directory"
              mkdir -p deployment/quiz/public

              echo "Copying standalone files..."
              if [ -d ".next/standalone" ]; then
                cp -r .next/standalone/* deployment/quiz/
              else
                echo "⚠️ No standalone directory found!"
              fi

              echo "Copying static files..."
              if [ -d ".next/static" ]; then
                cp -r .next/static deployment/quiz/.next/static
              else
                echo "⚠️ No static directory found!"
              fi

              echo "Copying project files..."
              cp package.json deployment/quiz/ || echo "⚠️ package.json not found!"
              cp -r public deployment/quiz/public || echo "⚠️ No public files found!"

              echo "Checking for server.js..."
              if [ -f "deployment/quiz/server.js" ]; then
                chmod +x deployment/quiz/server.js
              else
                echo "⚠️ server.js not found!"
              fi

         - name: FTP Deploy
           uses: SamKirkland/FTP-Deploy-Action@v4.3.4
           with:
              server: ${{ secrets.FTP_SERVER }}
              username: ${{ secrets.FTP_USERNAME }}
              password: ${{ secrets.FTP_PASSWORD }}
              local-dir: deployment/quiz/
              server-dir: /
              exclude: |
                 **/.git*
                 **/.git*/**
                 **/node_modules/**
                 README.md
                 .env*
